name: Build

on:
  pull_request:
  push:
    tags:
      - 'build*' # Push events to matching build* tags

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile query_fund.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: query-main
        path: dist